name: jellyfin
services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /DATA/AppData/jellyfin/cache:/cache
      - /DATA/AppData/media:/media

x-glass:
  title: Jellyfin
  tagline: Free media server to organize and stream movies, shows and music.
  description: Self-hosted media system to organize, manage and stream your own library.
  developer: Jellyfin Project
  category: multimedia
  tags: [media, streaming, movies, tv, music]
  architectures: [amd64, arm64]
  version: "10.11.11"
  updatedAt: "2026-08-25"
  icon: ./assets/icon.png
  background: ./assets/background.png
  screenshots:
    - ./assets/screenshot-1.png
    - ./assets/screenshot-2.png
  website: https://jellyfin.org/
  source: https://github.com/jellyfin/jellyfin
  docs: https://jellyfin.org/docs/
  entrypoint:
    main: jellyfin
    index: /
    portMap: "8096"
    scheme: http
  customInstall: true
  requirements:
    memory:
      minimum: 1GB
      recommended: 4GB+
    storage:
      minimum: 10GB
      recommended: 100GB+
    processor:
      minimum: Dual Core
      recommended: Quad Core
