name: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.3.2
    container_name: uptime-kuma
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - /DATA/AppData/uptime-kuma/data:/app/data

x-glass:
  title: Uptime Kuma
  tagline: Self-hosted uptime and service monitoring.
  description: Self-hosted tool to monitor the availability of services, hosts and endpoints.
  developer: Louis Lam
  category: devops
  tags: [monitoring, uptime, status-page, alerts, network]
  architectures: [amd64, arm64]
  version: "2.3.2"
  updatedAt: "2026-08-25"
  icon: ./assets/icon.svg
  background: ./assets/background.jpg
  screenshots:
    - ./assets/screenshot-1.jpg
    - ./assets/screenshot-2.jpg
    - ./assets/screenshot-3.png
    - ./assets/screenshot-4.jpg
    - ./assets/screenshot-5.jpg
  website: https://uptime.kuma.pet/
  source: https://github.com/louislam/uptime-kuma
  docs: https://github.com/louislam/uptime-kuma/wiki
  entrypoint:
    main: uptime-kuma
    index: /
    portMap: "3001"
    scheme: http
  customInstall: true
  requirements:
    memory:
      minimum: 256MB
      recommended: 512MB+
    storage:
      minimum: 1GB
      recommended: 5GB+
    processor:
      minimum: Single Core
      recommended: Dual Core
