name: home-assistant
services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2026.8.2
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - /DATA/AppData/home-assistant/config:/config

x-glass:
  title: Home Assistant
  tagline: Open source home automation platform.
  description: Self-hosted platform to integrate devices, build automations and control your smart home.
  developer: Open Home Foundation
  category: home
  tags: [smart-home, automation, iot, dashboard, home]
  architectures: [amd64, arm64]
  version: "2026.8.2"
  updatedAt: "2026-08-25"
  icon: ./assets/icon.png
  background: ./assets/background.png
  screenshots:
    - ./assets/screenshot-1.jpg
    - ./assets/screenshot-2.jpg
  website: https://www.home-assistant.io/
  source: https://github.com/home-assistant/core
  docs: https://www.home-assistant.io/docs/
  entrypoint:
    main: home-assistant
    index: /
    portMap: "8123"
    scheme: http
  customInstall: false
  requirements:
    memory:
      minimum: 1GB
      recommended: 2GB+
    storage:
      minimum: 16GB
      recommended: 32GB+
    processor:
      minimum: Dual Core
      recommended: Quad Core
